# Generated by Django 6.0.2 on 2026-02-19 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('documents', '0004_numbering_reset_and_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdocsequence',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_doc_sequences', to='companies.company'),
        ),
    ]
