# Generated by Django 5.1 on 2025-09-06 00:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('method', models.CharField(blank=True, max_length=50)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=200)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='company.company')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='invoices.invoice')),
            ],
            options={
                'ordering': ('-received_at', '-id'),
                'indexes': [models.Index(fields=['company', 'invoice', 'received_at'], name='payments_pa_company_b83d90_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('company', 'external_id'), name='uniq_payment_external_per_company')],
            },
        ),
    ]
