# Generated by Django 6.0.2 on 2026-02-15 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0012_ops_email_test'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='opsemailtest',
            new_name='ops_opsemai_created_fd37ae_idx',
            old_name='ops_opsemail_created_0c2b79_idx',
        ),
        migrations.RenameIndex(
            model_name='opsemailtest',
            new_name='ops_opsemai_status_5d99f2_idx',
            old_name='ops_opsemail_status_9c780a_idx',
        ),
    ]
