# Generated by ChatGPT (Stripe refund linkage)
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_rename_payments_ccap_company__c3c842_idx_payments_cl_company_4382e3_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="refunded_cents",
            field=models.BigIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="PaymentRefund",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("revision", models.BigIntegerField(default=0)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("cents", models.BigIntegerField(default=0)),
                ("status", models.CharField(choices=[("pending","Pending"),("succeeded","Succeeded"),("failed","Failed")], default="pending", max_length=20)),
                ("stripe_refund_id", models.CharField(blank=True, default="", max_length=80)),
                ("stripe_charge_id", models.CharField(blank=True, default="", max_length=80)),
                ("stripe_payment_intent_id", models.CharField(blank=True, default="", max_length=80)),
                ("memo", models.CharField(blank=True, default="", max_length=240)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="payment_refunds", to="companies.company")),
                ("payment", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="refunds", to="payments.payment")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="companies.employeeprofile")),
                ("updated_by_user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="payments_paymentrefund_updates", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["company","payment","created_at"], name="payments_ref_company_payment_created_idx"),
                    models.Index(fields=["company","stripe_refund_id"], name="payments_ref_company_stripe_refund_idx"),
                ],
            },
        ),
    ]
