# Generated by Django 6.0.2 on 2026-02-17 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_bankconnection_sync_cursor'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='banktransaction',
            new_name='integration_posted__087db4_idx',
            old_name='integrations_posted_d_7a1cdb_idx',
        ),
        migrations.RenameIndex(
            model_name='banktransaction',
            new_name='integration_is_pend_371d36_idx',
            old_name='integrations_is_pend_9c3a7f_idx',
        ),
    ]
