# Generated by Django 6.0.2 on 2026-02-18 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0004_rename_integrations_posted_d_7a1cdb_idx_integration_posted__087db4_idx_and_more'),
        ('integrations', '0006_bank_reconciliation_period'),
    ]

    operations = [
    ]
