# Generated by Django 6.0.2 on 2026-02-14 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0010_user_presence'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='userpresence',
            new_name='ops_userpre_company_f4154b_idx',
            old_name='ops_userpre_company_9f2c68_idx',
        ),
        migrations.RenameIndex(
            model_name='userpresence',
            new_name='ops_userpre_last_se_b58ff0_idx',
            old_name='ops_userpre_last_se_1e4a0d_idx',
        ),
    ]
