# Generated by Django 5.1 on 2025-09-06 00:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text="URL-safe key, e.g. 'starter', 'pro'.", unique=True)),
                ('name', models.CharField(max_length=100)),
                ('stripe_price_id', models.CharField(help_text='Stripe Price ID (price_...).', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('sort', models.PositiveIntegerField(default=0, help_text='Higher values show higher in plan lists.')),
                ('active', models.BooleanField(default=True)),
                ('trial_days', models.PositiveIntegerField(blank=True, help_text='Optional trial period (days).', null=True)),
                ('features', models.JSONField(blank=True, default=dict)),
                ('limits', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ('-sort', 'name'),
                'indexes': [models.Index(fields=['slug'], name='billing_sub_slug_65cd69_idx'), models.Index(fields=['active', 'sort'], name='billing_sub_active_2a21fe_idx')],
            },
        ),
        migrations.CreateModel(
            name='CompanySubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_customer_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('stripe_subscription_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('status', models.CharField(choices=[('incomplete', 'Incomplete'), ('trialing', 'Trialing'), ('active', 'Active'), ('past_due', 'Past due'), ('canceled', 'Canceled'), ('unpaid', 'Unpaid')], db_index=True, default='incomplete', max_length=20)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='company.company')),
                ('tier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='billing.subscriptiontier')),
            ],
            options={
                'verbose_name': 'Company subscription',
                'verbose_name_plural': 'Company subscriptions',
                'indexes': [models.Index(fields=['status', 'current_period_end'], name='billing_com_status_c06526_idx'), models.Index(fields=['stripe_customer_id'], name='billing_com_stripe__6adcb3_idx'), models.Index(fields=['stripe_subscription_id'], name='billing_com_stripe__d0f091_idx')],
            },
        ),
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_event_id', models.CharField(db_index=True, max_length=120, unique=True)),
                ('type', models.CharField(db_index=True, max_length=120)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('processed_ok', models.BooleanField(db_index=True, default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('message', models.TextField(blank=True, default='')),
                ('payment_external_id', models.CharField(blank=True, default='', max_length=200)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_logs', to='invoices.invoice')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['type', 'processed_ok'], name='billing_web_type_e6a399_idx'), models.Index(fields=['created_at'], name='billing_web_created_d3a366_idx')],
            },
        ),
    ]
