# Generated by Django 5.1 on 2025-08-28 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptiontier',
            name='features',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='subscriptiontier',
            name='limits',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
