# Generated by Django 5.1 on 2025-08-30 15:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_subscriptiontier_features_subscriptiontier_limits'),
        ('core', '0020_alter_client_options_alter_company_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_event_id', models.CharField(db_index=True, max_length=120, unique=True)),
                ('type', models.CharField(db_index=True, max_length=120)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('processed_ok', models.BooleanField(db_index=True, default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('message', models.TextField(blank=True, default='')),
                ('payment_external_id', models.CharField(blank=True, default='', max_length=200)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_logs', to='core.invoice')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
