# Generated by Django 6.0.2 on 2026-02-13 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_plan_tiers_interval_extra_seats'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='companysubscription',
            new_name='billing_com_plan_1b5666_idx',
            old_name='billing_com_plan_int_status_idx',
        ),
        migrations.RenameIndex(
            model_name='companysubscription',
            new_name='billing_com_trial_e_a6b689_idx',
            old_name='billing_com_trial_ends_idx',
        ),
    ]
