# Generated by Django 5.1 on 2025-09-01 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_webhooklog'),
        ('core', '0021_suggestion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companysubscription',
            options={'verbose_name': 'Company subscription', 'verbose_name_plural': 'Company subscriptions'},
        ),
        migrations.AlterModelOptions(
            name='subscriptiontier',
            options={'ordering': ('-sort', 'name')},
        ),
        migrations.AlterField(
            model_name='companysubscription',
            name='status',
            field=models.CharField(choices=[('incomplete', 'Incomplete'), ('trialing', 'Trialing'), ('active', 'Active'), ('past_due', 'Past due'), ('canceled', 'Canceled'), ('unpaid', 'Unpaid')], db_index=True, default='incomplete', max_length=20),
        ),
        migrations.AlterField(
            model_name='companysubscription',
            name='stripe_customer_id',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='companysubscription',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='companysubscription',
            name='tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='billing.subscriptiontier'),
        ),
        migrations.AlterField(
            model_name='subscriptiontier',
            name='slug',
            field=models.SlugField(help_text="URL-safe key, e.g. 'starter', 'pro'.", unique=True),
        ),
        migrations.AlterField(
            model_name='subscriptiontier',
            name='sort',
            field=models.PositiveIntegerField(default=0, help_text='Higher values show higher in plan lists.'),
        ),
        migrations.AlterField(
            model_name='subscriptiontier',
            name='stripe_price_id',
            field=models.CharField(help_text='Stripe Price ID (price_...).', max_length=200),
        ),
        migrations.AddIndex(
            model_name='subscriptiontier',
            index=models.Index(fields=['slug'], name='billing_sub_slug_65cd69_idx'),
        ),
        migrations.AddIndex(
            model_name='webhooklog',
            index=models.Index(fields=['type', 'processed_ok'], name='billing_web_type_e6a399_idx'),
        ),
    ]
