# Generated by ChatGPT on 2026-02-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0005_seed_plan_catalog"),
    ]

    operations = [
        migrations.AddField(
            model_name="companysubscription",
            name="last_stripe_event_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="companysubscription",
            index=models.Index(fields=["last_stripe_event_at"], name="bill_sub_last_evt_idx"),
        ),
    ]
