# Generated by ChatGPT Phase 4B

from __future__ import annotations

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OpsAlertEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("level", models.CharField(choices=[("info", "Info"), ("warn", "Warning"), ("error", "Error")], db_index=True, default="error", max_length=16)),
                ("source", models.CharField(choices=[("stripe_webhook", "Stripe webhook"), ("email", "Email"), ("slow_request", "Slow request")], db_index=True, default="email", max_length=32)),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField(blank=True, default="")),
                ("details", models.JSONField(blank=True, default=dict)),
                ("is_resolved", models.BooleanField(db_index=True, default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_by_email", models.EmailField(blank=True, default="", max_length=254)),
                (
                    "company",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="ops_alerts", to="companies.company"),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="opsalertevent",
            index=models.Index(fields=["source", "level", "created_at"], name="ops_opsaler_source_4d1b6e_idx"),
        ),
        migrations.AddIndex(
            model_name="opsalertevent",
            index=models.Index(fields=["company", "is_resolved", "created_at"], name="ops_opsaler_company_9977a6_idx"),
        ),
    ]
