# Generated by ChatGPT on 2026-02-17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
        ("ops", "0002_siteconfig_maintenance_mode"),
    ]

    operations = [
        migrations.CreateModel(
            name="QAIssue",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in_progress", "In progress"),
                            ("resolved", "Resolved"),
                            ("wont_fix", "Won't fix"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=24,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        db_index=True,
                        default="medium",
                        max_length=16,
                    ),
                ),
                (
                    "area",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Module/area (e.g., Invoices, Banking, Time).",
                        max_length=64,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                ("discovered_by_email", models.EmailField(blank=True, default="", max_length=254)),
                ("assigned_to_email", models.EmailField(blank=True, default="", max_length=254)),
                ("related_url", models.URLField(blank=True, default="")),
                ("steps_to_reproduce", models.TextField(blank=True, default="")),
                ("expected_behavior", models.TextField(blank=True, default="")),
                ("actual_behavior", models.TextField(blank=True, default="")),
                ("resolution_notes", models.TextField(blank=True, default="")),
                ("resolved_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="qa_issues",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                # Define indexes inside CreateModel options to avoid state.add_index
                # edge-cases during makemigrations/project_state evaluation.
                "indexes": [
                    models.Index(fields=["status", "severity", "created_at"], name="ops_qai_st_sev_cr_idx"),
                    models.Index(fields=["company", "status", "created_at"], name="ops_qai_co_st_cr_idx"),
                    models.Index(fields=["area", "status", "created_at"], name="ops_qai_ar_st_cr_idx"),
                ],
            },
        ),
    ]
