# Generated by ChatGPT on 2026-02-19
from django.db import migrations
from decimal import Decimal


def seed_plan_catalog(apps, schema_editor):
    PlanCatalog = apps.get_model("billing", "PlanCatalog")
    SeatAddonConfig = apps.get_model("billing", "SeatAddonConfig")

    # Create/ensure plans (display pricing; Stripe IDs can be filled later in Admin).
    defaults = [
        {
            "code": "starter",
            "name": "Starter",
            "sort_order": 10,
            "monthly_price": Decimal("19.99"),
            "annual_price": Decimal("199.99"),
            "included_seats": 1,
            "trial_days": 14,
        },
        {
            "code": "professional",
            "name": "Professional",
            "sort_order": 20,
            "monthly_price": Decimal("49.99"),
            "annual_price": Decimal("499.99"),
            "included_seats": 5,
            "trial_days": 14,
        },
        {
            "code": "premium",
            "name": "Premium",
            "sort_order": 30,
            "monthly_price": Decimal("99.99"),
            "annual_price": Decimal("999.99"),
            "included_seats": 10,
            "trial_days": 14,
        },
    ]

    for row in defaults:
        PlanCatalog.objects.update_or_create(code=row["code"], defaults=row)

    SeatAddonConfig.objects.update_or_create(
        id=1,
        defaults={
            "monthly_price": Decimal("9.99"),
            "annual_price": Decimal("99.99"),
        },
    )


def unseed(apps, schema_editor):
    # Keep data on reverse; no-op.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0004_plan_catalog"),
    ]

    operations = [
        migrations.RunPython(seed_plan_catalog, unseed),
    ]
