# Generated by Django 6.0.3 on 2026-07-21 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('intake', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notes', to='projects.project'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['company', 'is_archived', '-created_at'], name='intake_note_company_6694f0_idx'),
        ),
    ]
