# Generated by Django 6.0.3 on 2026-07-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='contact_first_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='note',
            name='contact_last_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='note',
            name='prospect_company_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
