# Generated by Django 6.0.3 on 2026-07-30 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import intake.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_company_books_closed_through'),
        ('clients', '0002_contact_optional_email_phone'),
        ('intake', '0003_note_prospect_identity'),
        ('projects', '0007_clientformtemplate_clientformquestion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=intake.models.note_attachment_path)),
                ('original_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=255)),
                ('size', models.PositiveBigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('created_at', 'pk'),
            },
        ),
        migrations.AddField(
            model_name='note',
            name='activity_type',
            field=models.CharField(choices=[('general', 'General note'), ('client_change', 'Client change'), ('decision', 'Decision'), ('question', 'Question'), ('issue', 'Issue'), ('meeting', 'Meeting note'), ('site_observation', 'Site observation')], default='general', max_length=30),
        ),
        migrations.AddField(
            model_name='note',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='note',
            name='follow_up_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='original_content',
            field=models.TextField(blank=True, help_text='Optional original email or source text retained for context.'),
        ),
        migrations.AddField(
            model_name='note',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='note',
            name='source_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='note',
            name='source_reference',
            field=models.CharField(blank=True, help_text='Email subject, message ID, document name, or another source reference.', max_length=500),
        ),
        migrations.AddField(
            model_name='note',
            name='source_type',
            field=models.CharField(choices=[('internal', 'Internal'), ('email', 'Email'), ('phone', 'Phone call'), ('meeting', 'Meeting'), ('client_form', 'Client form'), ('document', 'Document'), ('other', 'Other')], default='internal', max_length=30),
        ),
        migrations.AddField(
            model_name='note',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('action_required', 'Action required'), ('waiting_client', 'Waiting on client'), ('resolved', 'Resolved'), ('reference', 'Reference only')], default='open', max_length=30),
        ),
        migrations.AddField(
            model_name='note',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['company', 'project', 'status', '-created_at'], name='intake_note_company_6c432d_idx'),
        ),
        migrations.AddField(
            model_name='noteattachment',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='intake.note'),
        ),
        migrations.AddField(
            model_name='noteattachment',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='note_attachments', to=settings.AUTH_USER_MODEL),
        ),
    ]
