# Generated by Django 6.0.3 on 2026-07-30 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0004_noteattachment_note_activity_type_note_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('change', 'Change'), ('task', 'Task'), ('question', 'Question'), ('decision', 'Decision')], default='task', max_length=20)),
                ('title', models.CharField(max_length=500)),
                ('detail', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('waiting', 'Waiting'), ('resolved', 'Resolved'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('due_on', models.DateField(blank=True, null=True)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_activity_items', to=settings.AUTH_USER_MODEL)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_items', to='intake.note')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_activity_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('order', 'pk'),
                'indexes': [models.Index(fields=['status', 'due_on'], name='intake_acti_status_5a1c9c_idx')],
            },
        ),
    ]
