# Generated by Django 6.0.3 on 2026-07-30 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0005_activityitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', 'Activity created'), ('updated', 'Activity updated'), ('status_changed', 'Activity status changed'), ('attachment_added', 'Attachment added'), ('attachment_removed', 'Attachment removed'), ('item_added', 'Action item added'), ('item_updated', 'Action item updated'), ('item_status_changed', 'Action item status changed')], max_length=30)),
                ('description', models.CharField(max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_events', to=settings.AUTH_USER_MODEL)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='intake.note')),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
                'indexes': [models.Index(fields=['note', 'created_at'], name='intake_acti_note_id_01e4be_idx')],
            },
        ),
    ]
