# Generated by Django 6.0.3 on 2026-07-21 21:24

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=30)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('address_1', models.CharField(max_length=255)),
                ('address_2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('municipality', models.CharField(blank=True, max_length=100)),
                ('parcel_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('lead', 'Lead'), ('approved', 'Approved'), ('active', 'Active'), ('on_hold', 'On hold'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='lead', max_length=20)),
                ('billing_type', models.CharField(choices=[('hourly', 'Hourly'), ('flat_fee', 'Flat fee')], max_length=20)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('fixed_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='clients.client')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.company')),
            ],
            options={
                'ordering': ('-number', '-pk'),
                'indexes': [models.Index(fields=['company', 'status'], name='projects_pr_company_48dbe1_idx'), models.Index(fields=['company', 'number'], name='projects_pr_company_0fd278_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'number'), name='projects_company_number_unique'), models.CheckConstraint(condition=models.Q(models.Q(('billing_type', 'hourly'), ('fixed_fee__isnull', True), ('hourly_rate__isnull', False)), models.Q(('billing_type', 'flat_fee'), ('fixed_fee__isnull', False), ('hourly_rate__isnull', True)), _connector='OR'), name='projects_billing_fields_match_type')],
            },
        ),
        migrations.CreateModel(
            name='ProjectNumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=4)),
                ('last_value', models.PositiveSmallIntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_number_sequences', to='accounts.company')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('company', 'period'), name='projects_company_period_sequence_unique'), models.CheckConstraint(condition=models.Q(('last_value__lte', 999)), name='projects_sequence_at_most_999')],
            },
        ),
    ]
