# Generated by Django 5.1 on 2025-09-06 00:57

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('company', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('details', models.TextField(blank=True)),
                ('billing_type', models.CharField(choices=[('hourly', 'Hourly'), ('flat', 'Flat Rate')], default='hourly', max_length=10)),
                ('budget', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Optional monetary budget (in company currency).', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('start_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('estimated_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Optional estimate of hours.', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Used for hourly billing calculations.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='clients.client')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='company.company')),
                ('team', models.ManyToManyField(blank=True, related_name='team_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['company', 'number'], name='projects_pr_company_0fd278_idx'), models.Index(fields=['company', 'client', 'due_date'], name='projects_pr_company_023a89_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'number'), name='uniq_project_number_per_company')],
            },
        ),
    ]
