# Generated by Django 6.0.3 on 2026-07-21 21:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('billable', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('logged', 'Logged'), ('invoiced', 'Invoiced')], default='logged', max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.company')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='time_entries', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='time_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-start_time', '-pk'),
                'indexes': [models.Index(fields=['company', 'project', 'start_time'], name='projects_ti_company_fc90a0_idx'), models.Index(fields=['company', 'status', 'billable'], name='projects_ti_company_40fe31_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('end_time__isnull', True)), fields=('user',), name='projects_one_running_timer_per_user'), models.CheckConstraint(condition=models.Q(('end_time__isnull', True), ('end_time__gt', models.F('start_time')), _connector='OR'), name='projects_time_end_after_start'), models.CheckConstraint(condition=models.Q(('end_time__isnull', False), ('status', 'logged'), _connector='OR'), name='projects_running_time_is_logged')],
            },
        ),
    ]
