# Generated by Django 5.1 on 2025-09-06 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
