# Generated by Django 6.0.3 on 2026-07-21 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('projects', '0002_timeentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='line_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_entries', to='documents.lineitem'),
        ),
    ]
