# Generated by Django 6.0.3 on 2026-07-23 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_timeentry_line_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
