# Generated by Django 6.0.3 on 2026-07-23 13:26

import datetime

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('documents', '0003_payment_fee_amount_and_more'),
        ('projects', '0004_alter_project_postal_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='paused_duration',
            field=models.DurationField(default=datetime.timedelta),
        ),
        migrations.AddConstraint(
            model_name='timeentry',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__isnull', True), ('paused_at__isnull', True), _connector='OR'), name='projects_time_no_pause_after_stop'),
        ),
    ]
