# Generated by Django 6.0.3 on 2026-07-30 12:32

import uuid

import django.db.models.deletion
from django.db import migrations, models

import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_company_books_closed_through'),
        ('projects', '0006_alter_project_billing_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientFormTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('welcome_message', models.TextField(blank=True)),
                ('estimated_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.company')),
            ],
            options={
                'ordering': ('name', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='ClientFormQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(blank=True, max_length=255)),
                ('label', models.CharField(max_length=500)),
                ('help_text', models.CharField(blank=True, max_length=1000)),
                ('field_type', models.CharField(choices=[('short_text', 'Short text'), ('long_text', 'Long text'), ('email', 'Email'), ('phone', 'Phone'), ('number', 'Number'), ('date', 'Date'), ('select', 'Dropdown'), ('multi_select', 'Checkboxes'), ('yes_no', 'Yes / no'), ('file', 'File upload')], max_length=30)),
                ('required', models.BooleanField(default=False)),
                ('options', models.JSONField(blank=True, default=list)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='projects.clientformtemplate')),
            ],
            options={
                'ordering': ('order', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='ProjectClientForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('welcome_message', models.TextField(blank=True)),
                ('estimated_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('public_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('viewed', 'Opened'), ('submitted', 'Submitted')], default='draft', max_length=20)),
                ('recipient_name', models.CharField(max_length=255)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('email_subject', models.CharField(blank=True, max_length=255)),
                ('email_message', models.TextField(blank=True)),
                ('email_status', models.CharField(choices=[('not_sent', 'Not sent'), ('sent', 'Sent'), ('failed', 'Failed')], default='not_sent', max_length=20)),
                ('email_error', models.CharField(blank=True, max_length=100)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('saved_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('submission_notified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.company')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_forms', to='projects.project')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_forms', to='projects.clientformtemplate')),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='ProjectFormQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(blank=True, max_length=255)),
                ('label', models.CharField(max_length=500)),
                ('help_text', models.CharField(blank=True, max_length=1000)),
                ('field_type', models.CharField(choices=[('short_text', 'Short text'), ('long_text', 'Long text'), ('email', 'Email'), ('phone', 'Phone'), ('number', 'Number'), ('date', 'Date'), ('select', 'Dropdown'), ('multi_select', 'Checkboxes'), ('yes_no', 'Yes / no'), ('file', 'File upload')], max_length=30)),
                ('required', models.BooleanField(default=False)),
                ('options', models.JSONField(blank=True, default=list)),
                ('order', models.PositiveSmallIntegerField()),
                ('project_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='projects.projectclientform')),
                ('source_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.clientformquestion')),
            ],
            options={
                'ordering': ('order', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='ProjectFormAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.JSONField(blank=True, default=str)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='projects.projectformquestion')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectFormUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=projects.models.project_form_upload_path)),
                ('original_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=255)),
                ('size', models.PositiveBigIntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='upload', to='projects.projectformquestion')),
            ],
        ),
        migrations.AddConstraint(
            model_name='clientformtemplate',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='projects_company_form_template_name_unique'),
        ),
        migrations.AddConstraint(
            model_name='clientformquestion',
            constraint=models.UniqueConstraint(fields=('template', 'order'), name='projects_form_template_question_order_unique'),
        ),
        migrations.AddIndex(
            model_name='projectclientform',
            index=models.Index(fields=['company', 'project', 'status'], name='projects_pr_company_94445f_idx'),
        ),
        migrations.AddConstraint(
            model_name='projectformquestion',
            constraint=models.UniqueConstraint(fields=('project_form', 'order'), name='projects_project_form_question_order_unique'),
        ),
    ]
