# Generated by Django 6.0.2 on 2026-02-13 13:48

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('revision', models.BigIntegerField(default=0)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_by_device', models.UUIDField(blank=True, null=True)),
                ('name', models.CharField(max_length=160)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('email_from_name', models.CharField(blank=True, default='', max_length=160)),
                ('email_from_address', models.EmailField(blank=True, default='', max_length=254)),
                ('address1', models.CharField(blank=True, default='', max_length=200)),
                ('address2', models.CharField(blank=True, default='', max_length=200)),
                ('city', models.CharField(blank=True, default='', max_length=120)),
                ('state', models.CharField(blank=True, default='', max_length=2)),
                ('zip_code', models.CharField(blank=True, default='', max_length=12)),
                ('is_active', models.BooleanField(default=True)),
                ('require_2fa_for_admins_managers', models.BooleanField(default=False)),
                ('require_2fa_for_all', models.BooleanField(default=False)),
                ('updated_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('revision', models.BigIntegerField(default=0)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_by_device', models.UUIDField(blank=True, null=True)),
                ('display_name', models.CharField(blank=True, default='', max_length=160)),
                ('username_public', models.CharField(max_length=40)),
                ('role', models.CharField(choices=[('staff', 'Staff'), ('manager', 'Manager'), ('admin', 'Admin'), ('owner', 'Owner')], default='staff', max_length=20)),
                ('force_2fa', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('require_2fa_for_admins_managers', models.BooleanField(default=False)),
                ('require_2fa_for_all', models.BooleanField(default=False)),
                ('hired_at', models.DateField(blank=True, null=True)),
                ('terminated_at', models.DateField(blank=True, null=True)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cost_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('can_view_company_financials', models.BooleanField(default=False)),
                ('can_approve_time', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='companies.company')),
                ('updated_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyInvite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('revision', models.BigIntegerField(default=0)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_by_device', models.UUIDField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('username_public', models.CharField(max_length=40)),
                ('role', models.CharField(choices=[('staff', 'Staff'), ('manager', 'Manager'), ('admin', 'Admin'), ('owner', 'Owner')], default='staff', max_length=20)),
                ('force_2fa', models.BooleanField(default=False)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='companies.company')),
                ('updated_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.employeeprofile')),
            ],
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['name'], name='companies_c_name_2d8260_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['updated_at'], name='companies_c_updated_c5a19b_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['deleted_at'], name='companies_c_deleted_99a40f_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeprofile',
            index=models.Index(fields=['company', 'role'], name='companies_e_company_2eee39_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeprofile',
            index=models.Index(fields=['company', 'is_active'], name='companies_e_company_28e642_idx'),
        ),
        migrations.AddConstraint(
            model_name='employeeprofile',
            constraint=models.UniqueConstraint(fields=('company', 'username_public'), name='uniq_company_username_public'),
        ),
        migrations.AddConstraint(
            model_name='employeeprofile',
            constraint=models.UniqueConstraint(fields=('company', 'user'), name='uniq_company_user_profile'),
        ),
        migrations.AddIndex(
            model_name='companyinvite',
            index=models.Index(fields=['company', 'email'], name='companies_c_company_c2cd7f_idx'),
        ),
        migrations.AddIndex(
            model_name='companyinvite',
            index=models.Index(fields=['token'], name='companies_c_token_e28731_idx'),
        ),
    ]
