# Generated by Django 5.1 on 2025-08-29 00:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_payment_external_id_estimate_estimateitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='public_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
