# Generated by Django 5.1 on 2025-08-29 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_estimate_public_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='allow_reminders',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='last_reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='reminder_log',
            field=models.CharField(blank=True, default='', help_text="CSV of offsets sent or 'manual' entries", max_length=120),
        ),
    ]
