# Generated by Django 5.1 on 2025-08-29 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_invoice_allow_reminders_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('frequency', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='monthly', max_length=12)),
                ('start_date', models.DateField(help_text='First issue date.')),
                ('next_run_date', models.DateField(help_text='Next scheduled generation date.')),
                ('end_date', models.DateField(blank=True, null=True)),
                ('due_days', models.PositiveIntegerField(default=14, help_text='Days after issue for due date.')),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused')], default='active', max_length=12)),
                ('auto_email', models.BooleanField(default=True, help_text='Email the invoice automatically on generation.')),
                ('max_occurrences', models.PositiveIntegerField(blank=True, help_text='Stop after N issues (optional).', null=True)),
                ('occurrences_sent', models.PositiveIntegerField(default=0)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.client')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_plans', to='core.company')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.project')),
                ('template_invoice', models.ForeignKey(blank=True, help_text='Items/notes/tax copied each cycle.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.invoice')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
