# Generated by Django 5.1 on 2025-08-29 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_companymember_hourly_rate_companymember_job_title_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('generic', 'Generic'), ('invoice_created', 'Invoice created'), ('invoice_paid', 'Invoice paid'), ('estimate_accepted', 'Estimate accepted'), ('estimate_created', 'Estimate created'), ('estimate_converted', 'Estimate converted'), ('project_created', 'Project created'), ('time_added', 'Time added'), ('expense_added', 'Expense added')], default='generic', max_length=40)),
                ('text', models.CharField(max_length=240)),
                ('url', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_sent', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.company')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['recipient', 'read_at'], name='core_notifi_recipie_43dea6_idx'), models.Index(fields=['company', 'created_at'], name='core_notifi_company_42c6fd_idx')],
            },
        ),
    ]
