# Generated by Django 5.1 on 2025-08-29 17:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_estimate_accepted_at_estimate_accepted_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='public_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
