# Generated by Django 5.1 on 2025-08-29 18:39

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_estimate_public_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_entries', to='core.invoice'),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='is_billable',
            field=models.BooleanField(default=True),
        ),
    ]
