# Generated by Django 5.1 on 2025-08-29 19:13

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_project_hourly_rate_timeentry_invoice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='billable_markup_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percentage markup to apply when rebilling (e.g., 10.00 for 10%).', max_digits=5),
        ),
        migrations.AddField(
            model_name='expense',
            name='billable_note',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='expense',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='core.invoice'),
        ),
        migrations.AddField(
            model_name='expense',
            name='is_billable',
            field=models.BooleanField(default=False),
        ),
    ]
