# Generated by Django 5.1 on 2025-08-30 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_search_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='client',
            name='client_org_trgm',
        ),
        migrations.RemoveIndex(
            model_name='client',
            name='client_email_trgm',
        ),
        migrations.RemoveIndex(
            model_name='estimate',
            name='estimate_number_trgm',
        ),
        migrations.RemoveIndex(
            model_name='expense',
            name='expense_desc_trgm',
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='invoice_number_trgm',
        ),
        migrations.RemoveIndex(
            model_name='project',
            name='project_name_trgm',
        ),
        migrations.RemoveIndex(
            model_name='project',
            name='project_number_trgm',
        ),
    ]
