# Generated by Django 5.1 on 2025-08-30 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0017_remove_client_client_org_trgm_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notification',
            name='core_notifi_recipie_43dea6_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='core_notifi_company_42c6fd_idx',
        ),
        migrations.AddField(
            model_name='notification',
            name='target_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='notification',
            name='target_object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='text',
            field=models.CharField(max_length=280),
        ),
        migrations.AlterField(
            model_name='notification',
            name='url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['company', 'recipient', 'read_at', 'created_at'], name='core_notifi_company_8f1bcf_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'read_at', 'created_at'], name='core_notifi_recipie_52850f_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['target_content_type', 'target_object_id'], name='core_notifi_target__37b18d_idx'),
        ),
    ]
