# Generated by Django 5.1 on 2025-08-30 14:47

import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_estimate_public_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ('org', 'last_name', 'first_name', 'id')},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ('name', 'id')},
        ),
        migrations.AlterModelOptions(
            name='companyinvite',
            options={'ordering': ('-sent_at',)},
        ),
        migrations.AlterModelOptions(
            name='companymember',
            options={'ordering': ('-joined_at',)},
        ),
        migrations.AlterModelOptions(
            name='estimateitem',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ('-date', '-id')},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ('-issue_date', '-id')},
        ),
        migrations.AlterModelOptions(
            name='invoiceitem',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ('-received_at', '-id')},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('-created_at', '-id')},
        ),
        migrations.AlterModelOptions(
            name='timeentry',
            options={'ordering': ('-started_at', '-id')},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ('user',)},
        ),
        migrations.AlterField(
            model_name='estimate',
            name='public_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='billable_markup_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percentage markup to apply when rebilling, e.g. 10.00 for 10%.', max_digits=5),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['company', 'org'], name='core_client_company_edd723_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['company', 'email'], name='core_client_company_0a6423_idx'),
        ),
        migrations.AddIndex(
            model_name='estimate',
            index=models.Index(fields=['company', 'status', 'issue_date'], name='core_estima_company_cd1fa9_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['company', 'project', 'date'], name='core_expens_company_fe0226_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['company', 'status', 'issue_date'], name='core_invoic_company_572707_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['company', 'invoice', 'received_at'], name='core_paymen_company_442e9f_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['company', 'number'], name='core_projec_company_953af9_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['company', 'client', 'due_date'], name='core_projec_company_9c6313_idx'),
        ),
        migrations.AddIndex(
            model_name='timeentry',
            index=models.Index(fields=['project', 'user', 'started_at'], name='core_timeen_project_49fa7b_idx'),
        ),
        migrations.AddIndex(
            model_name='timeentry',
            index=models.Index(fields=['project', 'status', 'started_at'], name='core_timeen_project_8d978b_idx'),
        ),
        migrations.AddIndex(
            model_name='timeentry',
            index=models.Index(fields=['user', 'status', 'started_at'], name='core_timeen_user_id_fc3c30_idx'),
        ),
    ]
