# Generated by Django 6.0.2 on 2026-02-13 13:48

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('revision', models.BigIntegerField(default=0)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_by_device', models.UUIDField(blank=True, null=True)),
                ('code', models.CharField(blank=True, default='', max_length=24)),
                ('name', models.CharField(max_length=160)),
                ('type', models.CharField(choices=[('ASSET', 'Asset'), ('LIABILITY', 'Liability'), ('EQUITY', 'Equity'), ('INCOME', 'Income'), ('EXPENSE', 'Expense')], max_length=16)),
                ('normal_balance', models.CharField(choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit')], max_length=8)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['type', 'code', 'name'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('revision', models.BigIntegerField(default=0)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_by_device', models.UUIDField(blank=True, null=True)),
                ('entry_date', models.DateField(default=django.utils.timezone.localdate)),
                ('memo', models.CharField(blank=True, default='', max_length=240)),
                ('source_type', models.CharField(blank=True, default='', max_length=40)),
                ('source_id', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-entry_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JournalLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('revision', models.BigIntegerField(default=0)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_by_device', models.UUIDField(blank=True, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=240)),
                ('debit_cents', models.IntegerField(default=0)),
                ('credit_cents', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
