# Generated by Django 6.0.2 on 2026-02-13 19:00

from django.db import migrations, models


def forwards(apps, schema_editor):
    CompanySubscription = apps.get_model("billing", "CompanySubscription")
    # Map legacy plan codes to new tier codes.
    for sub in CompanySubscription.objects.all():
        if sub.plan == "standard":
            sub.plan = "starter"
        # legacy premium stays premium
        sub.save(update_fields=["plan"])


def backwards(apps, schema_editor):
    CompanySubscription = apps.get_model("billing", "CompanySubscription")
    for sub in CompanySubscription.objects.all():
        if sub.plan == "starter":
            sub.plan = "standard"
        # professional -> standard on downgrade
        elif sub.plan == "professional":
            sub.plan = "standard"
        sub.save(update_fields=["plan"])


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="companysubscription",
            name="seat_tier",
        ),
        migrations.AddField(
            model_name="companysubscription",
            name="billing_interval",
            field=models.CharField(choices=[("month", "Monthly"), ("year", "Annual")], default="month", max_length=10),
        ),
        migrations.AddField(
            model_name="companysubscription",
            name="extra_seats",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="companysubscription",
            name="plan",
            field=models.CharField(
                choices=[("starter", "Starter"), ("professional", "Professional"), ("premium", "Premium")],
                default="starter",
                max_length=20,
            ),
        ),
        migrations.RunPython(forwards, backwards),
        migrations.AlterIndexTogether(
            name="companysubscription",
            index_together=set(),
        ),
        migrations.AlterModelOptions(
            name="companysubscription",
            options={
                "indexes": [
                    models.Index(fields=["plan", "billing_interval", "status"], name="billing_com_plan_int_status_idx"),
                    models.Index(fields=["trial_ends_at"], name="billing_com_trial_ends_idx"),
                ]
            },
        ),
    ]
