# Generated by Django 5.1 on 2025-09-06 00:57

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('invoices', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(blank=True, max_length=200)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Entered in your company currency; non-negative.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('is_billable', models.BooleanField(default=False)),
                ('billable_markup_pct', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percentage markup to apply when rebilling, e.g. 10.00 for 10%.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('999.99'))])),
                ('billable_note', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='company.company')),
                ('invoice', models.ForeignKey(blank=True, help_text='If rebilled to a client, the invoice this expense was added to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='invoices.invoice')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='projects.project')),
            ],
            options={
                'ordering': ('-date', '-id'),
                'indexes': [models.Index(fields=['company', 'project', 'date'], name='expenses_ex_company_5e4d7c_idx'), models.Index(fields=['company', 'date'], name='expenses_ex_company_c0780e_idx'), models.Index(fields=['company', 'category'], name='expenses_ex_company_026674_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gte', Decimal('0.00'))), name='expense_amount_non_negative'), models.CheckConstraint(condition=models.Q(('billable_markup_pct__gte', Decimal('0.00'))), name='expense_markup_non_negative')],
            },
        ),
    ]
