# Generated by Django 6.0.2 on 2026-02-14 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0007_merge_20260214_0648'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='releasenote',
            new_name='ops_release_environ_2aebc9_idx',
            old_name='ops_releas_environment_8d0b27_idx',
        ),
        migrations.RenameIndex(
            model_name='releasenote',
            new_name='ops_release_build_v_9cf119_idx',
            old_name='ops_releas_build_ve_a0d8cf_idx',
        ),
        migrations.RenameIndex(
            model_name='releasenote',
            new_name='ops_release_build_s_8113ad_idx',
            old_name='ops_releas_build_sh_7d53f6_idx',
        ),
        migrations.RenameIndex(
            model_name='storagesmoketest',
            new_name='ops_storage_kind_d3ea22_idx',
            old_name='ops_storag_kind_3bf9aa_idx',
        ),
        migrations.RenameIndex(
            model_name='storagesmoketest',
            new_name='ops_storage_ok_b08282_idx',
            old_name='ops_storag_ok_4b4b4b_idx',
        ),
    ]
