# Generated by Django 6.0.2 on 2026-02-18 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0007_merge_20260218_0716'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='bankreconciliationperiod',
            new_name='integration_company_82e4d9_idx',
            old_name='intg_co_s_e_idx',
        ),
        migrations.RenameIndex(
            model_name='bankreconciliationperiod',
            new_name='integration_company_50f20a_idx',
            old_name='intg_co_status_idx',
        ),
        migrations.RenameIndex(
            model_name='banktransaction',
            new_name='integration_status_0ed5f6_idx',
            old_name='integrations_status_7d2f55_idx',
        ),
    ]
