# Generated by Django 5.1 on 2025-09-06 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org', models.CharField(blank=True, max_length=200, verbose_name='Client company')),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('address_1', models.CharField(blank=True, max_length=200, verbose_name='Address line 1')),
                ('address_2', models.CharField(blank=True, max_length=200, verbose_name='Address line 2')),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('zip_code', models.CharField(blank=True, max_length=20, verbose_name='ZIP / Postal code')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(help_text='The tenant company that owns this client record.', on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='company.company')),
            ],
            options={
                'verbose_name': 'client',
                'verbose_name_plural': 'clients',
                'ordering': ('org', 'last_name', 'first_name', 'id'),
                'indexes': [models.Index(fields=['company', 'org'], name='clients_cli_company_ee1e91_idx'), models.Index(fields=['company', 'email'], name='clients_cli_company_e994a2_idx'), models.Index(fields=['company', 'last_name', 'first_name'], name='clients_cli_company_12cdf7_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'email'), name='uniq_client_per_company_email')],
            },
        ),
    ]
