# Generated by ChatGPT on 2026-02-18

from django.db import migrations


class Migration(migrations.Migration):
    """No-op.

    Previous iterations renamed QA indexes, but the final index names are now
    created directly in 0003_qaiissue via CreateModel(options={"indexes": ...}).
    This migration is kept to preserve a stable linear migration chain.
    """

    dependencies = [
        ("ops", "0003_qaiissue"),
    ]

    operations = []
