# Generated by Django 5.1 on 2025-08-31 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accepted_privacy_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='accepted_tos_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
