# Generated by Django 6.0.3 on 2026-07-23 21:53

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='default_invoice_due_days',
            field=models.PositiveSmallIntegerField(default=30, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(365)]),
        ),
        migrations.AddField(
            model_name='company',
            name='default_invoice_terms',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='company',
            name='default_proposal_terms',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='company',
            name='default_tax_rate',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
