# Generated by ChatGPT for EZ360PM Pack 3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="force_logout_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
