# Generated by Django 6.0.3 on 2026-07-29 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_company_books_closed_through'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='books_closed_through',
        ),
    ]
