# Generated by Django 6.0.2 on 2026-02-18

from __future__ import annotations

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("integrations", "0004_bank_rules_and_tx_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="banktransaction",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="banktransaction",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_bank_transactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="banktransaction",
            name="suggested_existing_expense",
            field=models.ForeignKey(
                blank=True,
                help_text="Potential existing expense match suggested by heuristics (non-binding).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bank_transactions_suggested",
                to="expenses.expense",
            ),
        ),
        migrations.AddField(
            model_name="banktransaction",
            name="suggested_existing_expense_score",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name="banktransaction",
            index=models.Index(fields=["status"], name="integrations_status_7d2f55_idx"),
        ),
    ]
