# Generated by Django 6.0.2 on 2026-02-16 00:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_logo_storage'),
        ('payables', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='bill',
            new_name='payables_bi_company_e6dd6c_idx',
            old_name='payables_bi_company_3b9aa1_idx',
        ),
        migrations.RenameIndex(
            model_name='bill',
            new_name='payables_bi_company_f38c63_idx',
            old_name='payables_bi_company_97d4a0_idx',
        ),
        migrations.RenameIndex(
            model_name='bill',
            new_name='payables_bi_company_e36767_idx',
            old_name='payables_bi_company_8e7f3b_idx',
        ),
        migrations.AlterField(
            model_name='vendor',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payables_vendors', to='companies.company'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='updated_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_payables_vendor_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
