# Generated by Django 6.0.2 on 2026-02-16 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payables', '0002_rename_payables_bi_company_3b9aa1_idx_payables_bi_company_e6dd6c_idx_and_more'),
        ('payables', '0003_bill_attachment'),
    ]

    operations = [
    ]
