# Generated by ChatGPT on 2026-02-15

import uuid
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0001_initial"),
        ("companies", "0001_initial"),
        ("payables", "0003_bill_attachment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RecurringBillPlan",
            fields=[
                ("id", models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("revision", models.BigIntegerField(default=0)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("updated_by_device", models.UUIDField(blank=True, null=True)),
                (
                    "updated_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_recurringbillplan_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("frequency", models.CharField(choices=[("weekly", "Weekly"), ("monthly", "Monthly"), ("yearly", "Yearly")], default="monthly", max_length=12)),
                ("next_run", models.DateField(default=django.utils.timezone.localdate)),
                ("is_active", models.BooleanField(default=True)),
                ("auto_post", models.BooleanField(default=False)),
                ("amount_cents", models.IntegerField(default=0)),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="recurring_bill_plans", to="companies.company"),
                ),
                (
                    "vendor",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="recurring_bill_plans", to="payables.vendor"),
                ),
                (
                    "expense_account",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="recurring_bill_plans", to="accounting.account"),
                ),
                (
                    "created_by",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="recurring_bill_plans_created", to="companies.employeeprofile"),
                ),
            ],
            options={
                "ordering": ["next_run", "vendor__name"],
            },
        ),
        migrations.AddIndex(
            model_name="recurringbillplan",
            index=models.Index(fields=["company", "is_active", "next_run"], name="payables_re_company_0f8f6a_idx"),
        ),
        migrations.AddIndex(
            model_name="recurringbillplan",
            index=models.Index(fields=["company", "vendor"], name="payables_re_company_4d1e2e_idx"),
        ),
    ]
