# Generated by Django 6.0.2 on 2026-02-15 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_indexes_company_assignee_client_updated'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='project',
            new_name='projects_pr_company_17dfed_idx',
            old_name='proj_co_assignee_idx',
        ),
        migrations.RenameIndex(
            model_name='project',
            new_name='projects_pr_company_1d1576_idx',
            old_name='proj_co_client_idx',
        ),
        migrations.RenameIndex(
            model_name='project',
            new_name='projects_pr_company_358677_idx',
            old_name='proj_co_updated_idx',
        ),
    ]
