# Generated by Django 6.0.2 on 2026-02-13 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_performance_indexes'),
        ('payments', '0006_remove_clientcreditapplication_payments_cl_company_4382e3_idx_and_more'),
    ]

    operations = [
    ]
