# Generated by Django 6.0.3 on 2026-07-21 21:55

import uuid
from decimal import Decimal

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('projects', '0002_timeentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('proposal', 'Proposal'), ('invoice', 'Invoice')], max_length=20)),
                ('invoice_kind', models.CharField(blank=True, choices=[('retainer', 'Retainer'), ('final', 'Final')], max_length=20)),
                ('number', models.CharField(blank=True, max_length=30)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('viewed', 'Viewed'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('withdrawn', 'Withdrawn'), ('partially_paid', 'Partially paid'), ('paid', 'Paid'), ('void', 'Void')], default='draft', max_length=30)),
                ('issue_date', models.DateField(default=django.utils.timezone.localdate)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('credit_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('body_sections', models.JSONField(blank=True, default=list)),
                ('terms', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('accept_payments', models.BooleanField(default=False)),
                ('public_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_by_name', models.CharField(blank=True, max_length=255)),
                ('accepted_by_email', models.EmailField(blank=True, max_length=254)),
                ('accepted_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('acceptance_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.company')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='projects.project')),
                ('source_proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='derived_invoices', to='documents.document')),
            ],
            options={
                'ordering': ('-issue_date', '-number', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='DocumentNumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('proposal', 'Proposal'), ('invoice', 'Invoice')], max_length=20)),
                ('period', models.CharField(max_length=2)),
                ('last_value', models.PositiveIntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_number_sequences', to='accounts.company')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination_invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credits_received', to='documents.document')),
                ('source_invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credits_given', to='documents.document')),
            ],
        ),
        migrations.CreateModel(
            name='LineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('description', models.CharField(max_length=255)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('tax_rate', models.DecimalField(decimal_places=3, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('line_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='documents.document')),
            ],
            options={
                'ordering': ('order', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('method', models.CharField(choices=[('stripe', 'Stripe'), ('check', 'Check'), ('cash', 'Cash'), ('other', 'Other')], max_length=20)),
                ('received_at', models.DateField(default=django.utils.timezone.localdate)),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='documents.document')),
            ],
            options={
                'ordering': ('-received_at', '-created_at', '-pk'),
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['company', 'doc_type', 'status'], name='documents_d_company_3ea091_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['company', 'project', 'doc_type'], name='documents_d_company_ffbec7_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['company', 'due_date'], name='documents_d_company_31fa04_idx'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(fields=('company', 'doc_type', 'number'), name='documents_company_type_number_unique'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('doc_type', 'invoice'), ('due_date__isnull', False)), models.Q(('doc_type', 'proposal'), ('due_date__isnull', True)), _connector='OR'), name='documents_due_date_matches_type'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('doc_type', 'invoice'), ('invoice_kind__in', ('retainer', 'final'))), models.Q(('doc_type', 'proposal'), ('invoice_kind', '')), _connector='OR'), name='documents_kind_matches_type'),
        ),
        migrations.AddConstraint(
            model_name='documentnumbersequence',
            constraint=models.UniqueConstraint(fields=('company', 'doc_type', 'period'), name='documents_company_type_period_sequence_unique'),
        ),
        migrations.AddConstraint(
            model_name='invoicecredit',
            constraint=models.CheckConstraint(condition=models.Q(('source_invoice', models.F('destination_invoice')), _negated=True), name='documents_credit_distinct_invoices'),
        ),
        migrations.AddConstraint(
            model_name='invoicecredit',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='documents_credit_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='lineitem',
            constraint=models.UniqueConstraint(fields=('document', 'order'), name='documents_line_order_unique'),
        ),
        migrations.AddConstraint(
            model_name='lineitem',
            constraint=models.CheckConstraint(condition=models.Q(('rate__gte', 0), ('quantity__gt', 0), ('tax_rate__gte', 0)), name='documents_line_values_nonnegative'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['document', 'received_at'], name='documents_p_documen_8b2834_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='documents_payment_amount_positive'),
        ),
    ]
