# Generated by Django 6.0.3 on 2026-07-22 22:16

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_documentdelivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='fee_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Processing fee withheld by the provider (0 for manual payments).', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('fee_amount__gte', 0)), name='documents_payment_fee_nonnegative'),
        ),
    ]
