# Generated by Django 6.0.3 on 2026-07-23 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_payment_fee_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentdelivery',
            name='dedupe_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('viewed', 'Link opened'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('withdrawn', 'Withdrawn'), ('partially_paid', 'Partially paid'), ('paid', 'Paid'), ('void', 'Void')], default='draft', max_length=30),
        ),
        migrations.AlterField(
            model_name='documentdelivery',
            name='purpose',
            field=models.CharField(choices=[('client_document', 'Client document'), ('acceptance_notification', 'Acceptance notification'), ('payment_notification', 'Payment notification')], default='client_document', max_length=30),
        ),
        migrations.AddConstraint(
            model_name='documentdelivery',
            constraint=models.UniqueConstraint(condition=models.Q(('dedupe_key', ''), _negated=True), fields=('dedupe_key',), name='documents_delivery_dedupe_key_unique'),
        ),
    ]
