# Generated by Django 6.0.3 on 2026-07-23 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_documentdelivery_dedupe_key_alter_document_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='fee_pending',
            field=models.BooleanField(default=False, help_text='Stripe has not yet supplied the final processing fee.'),
        ),
    ]
