# Generated by Django 6.0.3 on 2026-07-23 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_payment_fee_pending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentdelivery',
            name='purpose',
            field=models.CharField(choices=[('client_document', 'Client document'), ('acceptance_notification', 'Acceptance notification'), ('decline_notification', 'Decline notification'), ('payment_notification', 'Payment notification')], default='client_document', max_length=30),
        ),
    ]
