# Generated by Django 6.0.3 on 2026-07-25 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_paymentfeereconciliationattempt'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='paymentadjustment',
            new_name='documents_p_company_61e9fb_idx',
            old_name='documents_p_company_6ae534_idx',
        ),
        migrations.RenameIndex(
            model_name='paymentadjustment',
            new_name='documents_p_payment_b3be31_idx',
            old_name='documents_p_payment_797d69_idx',
        ),
    ]
