# Generated by Django 6.0.3 on 2026-07-25 13:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_company_books_closed_through'),
        ('documents', '0009_rename_documents_p_company_6ae534_idx_documents_p_company_61e9fb_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeWebhookFailure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(blank=True, max_length=255)),
                ('event_type', models.CharField(max_length=100)),
                ('object_id', models.CharField(blank=True, max_length=255)),
                ('error_code', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('open', 'Needs attention'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('attempt_count', models.PositiveIntegerField(default=1)),
                ('first_failed_at', models.DateTimeField(auto_now_add=True)),
                ('last_failed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stripe_webhook_failures', to='accounts.company')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_stripe_webhook_failures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('status', '-last_failed_at', '-pk'),
                'indexes': [models.Index(fields=['status', 'last_failed_at'], name='doc_stripe_failure_queue_idx'), models.Index(fields=['company', 'status'], name='doc_stripe_failure_company_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('event_id', ''), _negated=True), fields=('event_id',), name='documents_stripe_failure_event_unique')],
            },
        ),
    ]
