# Generated by Django 6.0.3 on 2026-07-29 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_merge_delivery_follow_ups_and_stripe_failures'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='paymentadjustment',
            name='documents_p_company_61e9fb_idx',
        ),
        migrations.RemoveIndex(
            model_name='paymentadjustment',
            name='documents_p_payment_b3be31_idx',
        ),
        migrations.RemoveConstraint(
            model_name='paymentadjustment',
            name='documents_adjustment_amount_nonzero',
        ),
        migrations.RemoveConstraint(
            model_name='paymentadjustment',
            name='documents_adjustment_provider_company_unique',
        ),
        migrations.RemoveIndex(
            model_name='paymentfeereconciliationattempt',
            name='doc_fee_company_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='paymentfeereconciliationattempt',
            name='doc_fee_payment_attempt_idx',
        ),
        migrations.RemoveIndex(
            model_name='stripewebhookfailure',
            name='doc_stripe_failure_queue_idx',
        ),
        migrations.RemoveIndex(
            model_name='stripewebhookfailure',
            name='doc_stripe_failure_company_idx',
        ),
        migrations.RemoveConstraint(
            model_name='stripewebhookfailure',
            name='documents_stripe_failure_event_unique',
        ),
        migrations.RemoveConstraint(
            model_name='payment',
            name='documents_payment_current_fee_nonnegative',
        ),
        migrations.RemoveField(
            model_name='paymentfeereconciliationattempt',
            name='company',
        ),
        migrations.RemoveField(
            model_name='paymentfeereconciliationattempt',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='stripewebhookfailure',
            name='company',
        ),
        migrations.RemoveField(
            model_name='stripewebhookfailure',
            name='resolved_by',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='fee_current_amount',
        ),
        migrations.DeleteModel(
            name='PaymentAdjustment',
        ),
        migrations.DeleteModel(
            name='PaymentFeeReconciliationAttempt',
        ),
        migrations.DeleteModel(
            name='StripeWebhookFailure',
        ),
    ]
