# Generated by Django 6.0.3 on 2026-07-29 18:27

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_company_books_closed_through'),
        ('documents', '0012_remove_paymentadjustment_documents_p_company_61e9fb_idx_and_more'),
        ('projects', '0006_alter_project_billing_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='deposit_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Current amount due on a deposit invoice while total retains the full project value.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddField(
            model_name='document',
            name='source_invoice',
            field=models.ForeignKey(blank=True, help_text='Deposit invoice from which this final invoice was generated.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='follow_up_invoices', to='documents.document'),
        ),
        migrations.AlterField(
            model_name='document',
            name='invoice_kind',
            field=models.CharField(blank=True, choices=[('retainer', 'Deposit / retainer'), ('final', 'Final')], max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.CheckConstraint(condition=models.Q(('deposit_amount__isnull', True), models.Q(('deposit_amount__gt', 0), ('doc_type', 'invoice'), ('invoice_kind', 'retainer')), _connector='OR'), name='documents_deposit_matches_retainer'),
        ),
    ]
