# Generated by Django 6.0.3 on 2026-07-30 15:59

import django.db.models.deletion
from django.db import migrations, models


def mark_existing_deliveries_as_django(apps, schema_editor):
    DocumentDelivery = apps.get_model('documents', 'DocumentDelivery')
    DocumentDelivery.objects.filter(provider='').update(provider='django')


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0013_document_deposit_amount_document_source_invoice_and_more'),
        ('projects', '0007_clientformtemplate_clientformquestion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('django', 'Django email backend'), ('resend', 'Resend')], default='resend', max_length=20)),
                ('event_id', models.CharField(max_length=255)),
                ('event_type', models.CharField(max_length=50)),
                ('provider_message_id', models.CharField(blank=True, max_length=255)),
                ('occurred_at', models.DateTimeField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-occurred_at', '-pk'),
                'constraints': [models.UniqueConstraint(fields=('provider', 'event_id'), name='documents_email_event_provider_id_unique')],
            },
        ),
        migrations.AddField(
            model_name='documentdelivery',
            name='last_event_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentdelivery',
            name='project_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='email_deliveries', to='projects.projectclientform'),
        ),
        migrations.AddField(
            model_name='documentdelivery',
            name='provider',
            field=models.CharField(blank=True, choices=[('django', 'Django email backend'), ('resend', 'Resend')], max_length=20),
        ),
        migrations.RunPython(mark_existing_deliveries_as_django, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='documentdelivery',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='documents.document'),
        ),
        migrations.AlterField(
            model_name='documentdelivery',
            name='purpose',
            field=models.CharField(choices=[('client_document', 'Client document'), ('client_follow_up', 'Client follow-up'), ('acceptance_notification', 'Acceptance notification'), ('decline_notification', 'Decline notification'), ('payment_notification', 'Payment notification'), ('client_form', 'Client form'), ('client_form_submission', 'Form submission notification')], default='client_document', max_length=30),
        ),
        migrations.AlterField(
            model_name='documentdelivery',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('delayed', 'Delivery delayed'), ('bounced', 'Bounced'), ('complained', 'Marked as spam'), ('suppressed', 'Suppressed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='documentdelivery',
            index=models.Index(fields=['project_form', 'status'], name='documents_d_project_a99832_idx'),
        ),
        migrations.AddIndex(
            model_name='documentdelivery',
            index=models.Index(fields=['provider', 'provider_message_id'], name='documents_d_provide_d034c6_idx'),
        ),
        migrations.AddConstraint(
            model_name='documentdelivery',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('document__isnull', False), ('project_form__isnull', True)), models.Q(('document__isnull', True), ('project_form__isnull', False)), _connector='OR'), name='documents_delivery_has_one_target'),
        ),
        migrations.AddConstraint(
            model_name='documentdelivery',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('project_form__isnull', False), ('purpose__in', ('client_form', 'client_form_submission'))), models.Q(('document__isnull', False), ('purpose__in', ('client_document', 'client_follow_up', 'acceptance_notification', 'decline_notification', 'payment_notification'))), _connector='OR'), name='documents_delivery_purpose_matches_target'),
        ),
        migrations.AddField(
            model_name='emailwebhookevent',
            name='delivery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provider_events', to='documents.documentdelivery'),
        ),
        migrations.AddIndex(
            model_name='emailwebhookevent',
            index=models.Index(fields=['provider', 'provider_message_id'], name='documents_e_provide_0a65c2_idx'),
        ),
    ]
