# Generated by Django 6.0.3 on 2026-07-30 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0014_emailwebhookevent_documentdelivery_last_event_at_and_more'),
        ('projects', '0007_clientformtemplate_clientformquestion_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='documentdelivery',
            name='documents_d_provide_d034c6_idx',
        ),
        migrations.AddConstraint(
            model_name='documentdelivery',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_message_id', ''), _negated=True), fields=('provider', 'provider_message_id'), name='documents_delivery_provider_message_unique'),
        ),
    ]
