# Generated by Django 6.0.3 on 2026-08-01 11:41

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0015_remove_documentdelivery_documents_d_provide_d034c6_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='refunded_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total refunded back to the client for this payment.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('refunded_amount__gte', 0), ('refunded_amount__lte', models.F('amount'))), name='documents_payment_refund_within_amount'),
        ),
    ]
