# Generated by Django 6.0.3 on 2026-08-01 15:23

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def backfill_refund_history(apps, schema_editor):
    Payment = apps.get_model("documents", "Payment")
    PaymentRefund = apps.get_model("documents", "PaymentRefund")
    rows = [
        PaymentRefund(
            payment_id=payment.pk,
            amount=payment.refunded_amount,
            effective_at=payment.received_at,
            provider="legacy",
            reference="Migrated cumulative refund total",
        )
        for payment in Payment.objects.exclude(refunded_amount=0).iterator()
    ]
    PaymentRefund.objects.bulk_create(rows)


def remove_backfilled_refund_history(apps, schema_editor):
    PaymentRefund = apps.get_model("documents", "PaymentRefund")
    PaymentRefund.objects.filter(
        provider="legacy",
        reference="Migrated cumulative refund total",
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0016_payment_refunded_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('effective_at', models.DateField(default=django.utils.timezone.localdate)),
                ('provider', models.CharField(choices=[('manual', 'Recorded manually'), ('stripe', 'Stripe'), ('legacy', 'Migrated legacy total')], default='manual', max_length=20)),
                ('provider_ref', models.CharField(blank=True, max_length=255)),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_payment_refunds', to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='documents.payment')),
            ],
            options={
                'ordering': ('-effective_at', '-created_at', '-pk'),
                'indexes': [models.Index(fields=['payment', 'effective_at'], name='documents_p_payment_7694b4_idx'), models.Index(fields=['effective_at'], name='documents_p_effecti_1fe761_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='documents_refund_amount_positive'), models.UniqueConstraint(condition=models.Q(('provider_ref', ''), _negated=True), fields=('provider', 'provider_ref'), name='documents_refund_provider_ref_unique')],
            },
        ),
        migrations.CreateModel(
            name='StripeWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=255, unique=True)),
                ('event_type', models.CharField(max_length=100)),
                ('object_id', models.CharField(blank=True, max_length=255)),
                ('payment_intent_id', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('ignored', 'Ignored'), ('failed', 'Retry required'), ('requires_review', 'Needs review')], default='pending', max_length=20)),
                ('attempt_count', models.PositiveIntegerField(default=1)),
                ('error_code', models.CharField(blank=True, max_length=100)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('last_attempt_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stripe_events', to='documents.payment')),
            ],
            options={
                'ordering': ('status', '-last_attempt_at', '-pk'),
                'indexes': [models.Index(fields=['status', 'last_attempt_at'], name='documents_s_status_be6987_idx'), models.Index(fields=['payment_intent_id'], name='documents_s_payment_bc96b1_idx')],
            },
        ),
        migrations.RunPython(
            backfill_refund_history,
            remove_backfilled_refund_history,
        ),
    ]
