# Generated by Django 6.0.2 on 2026-02-13 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_client_credit_application'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='clientcreditapplication',
            new_name='payments_cl_company_4382e3_idx',
            old_name='payments_ccap_company__c3c842_idx',
        ),
        migrations.RenameIndex(
            model_name='clientcreditapplication',
            new_name='payments_cl_company_d51c22_idx',
            old_name='payments_ccap_company__6bd8f3_idx',
        ),
        migrations.AddField(
            model_name='clientcreditapplication',
            name='updated_by_device',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientcreditapplication',
            name='updated_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
