# Generated by ChatGPT on 2026-02-15
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="client",
            index=models.Index(fields=["company", "email"], name="crm_client_company_email_idx"),
        ),
    ]
