# Generated by Django 6.0.2 on 2026-02-16 02:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payables', '0004_merge_20260215_2109'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='billattachment',
            new_name='payables_bi_bill_id_6ddb35_idx',
            old_name='payables_ba_bill_idx',
        ),
        migrations.AlterField(
            model_name='billattachment',
            name='updated_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
