# Generated by Django 6.0.2 on 2026-02-16 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payables', '0004_recurring_bill_plan'),
        ('payables', '0005_rename_payables_ba_bill_idx_payables_bi_bill_id_6ddb35_idx_and_more'),
    ]

    operations = [
    ]
