# Generated by Django 6.0.2 on 2026-02-16 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payables', '0006_merge_20260216_0630'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='recurringbillplan',
            new_name='payables_re_company_cc38e9_idx',
            old_name='payables_re_company_0f8f6a_idx',
        ),
        migrations.RenameIndex(
            model_name='recurringbillplan',
            new_name='payables_re_company_47965e_idx',
            old_name='payables_re_company_4d1e2e_idx',
        ),
        migrations.AlterField(
            model_name='recurringbillplan',
            name='updated_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
