# Generated by Django 6.0.2 on 2026-02-14 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0005_merge_20260213_2307'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='backuprestoretest',
            new_name='ops_backupr_outcome_24afbe_idx',
            old_name='ops_backupre_outcome_2cfed5_idx',
        ),
        migrations.RenameIndex(
            model_name='backuprun',
            new_name='ops_backupr_status_bf756b_idx',
            old_name='ops_backupru_status_7c705f_idx',
        ),
        migrations.AlterField(
            model_name='opsalertevent',
            name='source',
            field=models.CharField(choices=[('stripe_webhook', 'Stripe webhook'), ('email', 'Email'), ('slow_request', 'Slow request'), ('auth', 'Auth'), ('throttle', 'Throttle'), ('launch_gate', 'Launch gate'), ('backup', 'Backup'), ('restore_test', 'Restore test')], db_index=True, default='email', max_length=32),
        ),
    ]
