# Generated by Django 6.0.2 on 2026-02-14 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0006_rename_ops_backupre_outcome_2cfed5_idx_ops_backupr_outcome_24afbe_idx_and_more'),
        ('ops', '0006_storage_smoke_tests'),
    ]

    operations = [
    ]
