# Generated by Django 6.0.2 on 2026-02-13 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_payment_refunds_and_refunded_cents'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='paymentrefund',
            new_name='payments_pa_company_358cef_idx',
            old_name='payments_ref_company_payment_created_idx',
        ),
        migrations.RenameIndex(
            model_name='paymentrefund',
            new_name='payments_pa_company_f46bc1_idx',
            old_name='payments_ref_company_stripe_refund_idx',
        ),
        migrations.AddField(
            model_name='paymentrefund',
            name='updated_by_device',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentrefund',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_refunds', to='payments.payment'),
        ),
        migrations.AlterField(
            model_name='paymentrefund',
            name='updated_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
