# Generated by Django 6.0.2 on 2026-02-14 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='opsalertevent',
            new_name='ops_opsaler_source_5b6301_idx',
            old_name='ops_opsaler_source_4d1b6e_idx',
        ),
        migrations.RenameIndex(
            model_name='opsalertevent',
            new_name='ops_opsaler_company_04ea1b_idx',
            old_name='ops_opsaler_company_9977a6_idx',
        ),
    ]
