# Generated by Django 6.0.2 on 2026-02-15 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0013_ops_probe_event'),
        ('ops', '0013_rename_ops_opsemail_created_0c2b79_idx_ops_opsemai_created_fd37ae_idx_and_more'),
    ]

    operations = [
    ]
