# Generated by Django 6.0.2 on 2026-02-15 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0014_merge_20260215_1400'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='opsprobeevent',
            new_name='ops_opsprob_kind_a5da2a_idx',
            old_name='ops_opsprob_kind_8ad0a5_idx',
        ),
        migrations.AlterField(
            model_name='opsalertevent',
            name='source',
            field=models.CharField(choices=[('stripe_webhook', 'Stripe webhook'), ('email', 'Email'), ('slow_request', 'Slow request'), ('auth', 'Auth'), ('throttle', 'Throttle'), ('launch_gate', 'Launch gate'), ('backup', 'Backup'), ('restore_test', 'Restore test'), ('probe', 'Probe')], db_index=True, default='email', max_length=32),
        ),
    ]
