# Generated by Django 6.0.2 on 2026-02-14 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0002_rename_ops_opsaler_source_4d1b6e_idx_ops_opsaler_source_5b6301_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opsalertevent',
            name='source',
            field=models.CharField(choices=[('stripe_webhook', 'Stripe webhook'), ('email', 'Email'), ('auth', 'Auth'), ('throttle', 'Throttle'), ('slow_request', 'Slow request')], db_index=True, default='email', max_length=32),
        ),
    ]
