# Generated by Django 6.0.2 on 2026-02-14 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0003_alter_opsalertevent_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opsalertevent',
            name='source',
            field=models.CharField(choices=[('stripe_webhook', 'Stripe webhook'), ('email', 'Email'), ('slow_request', 'Slow request')], db_index=True, default='email', max_length=32),
        ),
    ]
