# Generated by Django 6.0.2 on 2026-02-17 04:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('ops_alert_webhook_enabled', models.BooleanField(default=False)),
                ('ops_alert_webhook_url', models.URLField(blank=True, default='')),
                ('ops_alert_webhook_timeout_seconds', models.DecimalField(decimal_places=2, default=2.5, max_digits=5)),
                ('ops_alert_email_enabled', models.BooleanField(default=False)),
                ('ops_alert_email_recipients', models.TextField(blank=True, default='', help_text='Comma-separated list of recipient email addresses.')),
                ('ops_alert_email_min_level', models.CharField(choices=[('info', 'Info'), ('warn', 'Warning'), ('error', 'Error')], default='error', help_text='Minimum alert level to email (inclusive).', max_length=16)),
                ('ops_alert_noise_path_prefixes', models.TextField(blank=True, default='', help_text='One per line. If details.path starts with any prefix, the alert will be ignored.')),
                ('ops_alert_noise_user_agents', models.TextField(blank=True, default='', help_text='One per line. If details.user_agent contains any token (case-insensitive), the alert will be ignored.')),
                ('ops_alert_dedup_minutes', models.PositiveSmallIntegerField(default=10, help_text='Deduplicate identical open alerts within this many minutes (0 disables).')),
                ('ops_alert_prune_resolved_after_days', models.PositiveSmallIntegerField(default=30, help_text='Resolved alerts older than this many days may be pruned.')),
                ('ops_snooze_prune_after_days', models.PositiveSmallIntegerField(default=30, help_text='Expired snoozes older than this many days may be pruned (for audit cleanliness).')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ops Site Config',
                'verbose_name_plural': 'Ops Site Config',
            },
        ),
        migrations.CreateModel(
            name='BackupRestoreTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tested_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('outcome', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail')], db_index=True, default='pass', max_length=8)),
                ('notes', models.TextField(blank=True, default='')),
                ('tested_by_email', models.EmailField(blank=True, default='', max_length=254)),
                ('details', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-tested_at'],
                'indexes': [models.Index(fields=['outcome', 'tested_at'], name='ops_backupr_outcome_24afbe_idx')],
            },
        ),
        migrations.CreateModel(
            name='BackupRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], db_index=True, default='success', max_length=16)),
                ('storage', models.CharField(blank=True, default='', max_length=64)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('notes', models.TextField(blank=True, default='')),
                ('initiated_by_email', models.EmailField(blank=True, default='', max_length=254)),
                ('details', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='ops_backupr_status_bf756b_idx')],
            },
        ),
        migrations.CreateModel(
            name='LaunchGateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=64, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('is_complete', models.BooleanField(db_index=True, default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_launch_gate_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='OpsEmailTest',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('to_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('backend', models.CharField(blank=True, default='', max_length=255)),
                ('from_email', models.CharField(blank=True, default='', max_length=254)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed')], default='sent', max_length=20)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True, default='')),
                ('initiated_by_email', models.EmailField(blank=True, default='', max_length=254)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='ops_opsemai_created_fd37ae_idx'), models.Index(fields=['status', 'created_at'], name='ops_opsemai_status_5d99f2_idx')],
            },
        ),
        migrations.CreateModel(
            name='OpsProbeEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('kind', models.CharField(choices=[('sentry_test_error', 'Sentry test error'), ('alert_test', 'Alert test')], db_index=True, max_length=32)),
                ('status', models.CharField(choices=[('triggered', 'Triggered'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='triggered', max_length=16)),
                ('initiated_by_email', models.EmailField(blank=True, default='', max_length=254)),
                ('details', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['kind', 'status', 'created_at'], name='ops_opsprob_kind_a5da2a_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReleaseNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('environment', models.CharField(blank=True, db_index=True, default='', help_text='Deployment environment (dev/staging/prod). Optional, but recommended.', max_length=24)),
                ('build_version', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('build_sha', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('title', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_published', models.BooleanField(db_index=True, default=True, help_text='If disabled, note remains visible to staff but excluded from summaries.')),
                ('created_by_email', models.EmailField(blank=True, default='', max_length=254)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['environment', 'created_at'], name='ops_release_environ_2aebc9_idx'), models.Index(fields=['build_version', 'created_at'], name='ops_release_build_v_9cf119_idx'), models.Index(fields=['build_sha', 'created_at'], name='ops_release_build_s_8113ad_idx')],
            },
        ),
        migrations.CreateModel(
            name='OpsAlertEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('level', models.CharField(choices=[('info', 'Info'), ('warn', 'Warning'), ('error', 'Error')], db_index=True, default='error', max_length=16)),
                ('source', models.CharField(choices=[('stripe_webhook', 'Stripe webhook'), ('email', 'Email'), ('slow_request', 'Slow request'), ('auth', 'Auth'), ('throttle', 'Throttle'), ('launch_gate', 'Launch gate'), ('backup', 'Backup'), ('restore_test', 'Restore test'), ('ops_dashboard', 'Ops dashboard'), ('probe', 'Probe')], db_index=True, default='email', max_length=32)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField(blank=True, default='')),
                ('details', models.JSONField(blank=True, default=dict)),
                ('is_resolved', models.BooleanField(db_index=True, default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by_email', models.EmailField(blank=True, default='', max_length=254)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ops_alerts', to='companies.company')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['source', 'level', 'created_at'], name='ops_opsaler_source_5b6301_idx'), models.Index(fields=['company', 'is_resolved', 'created_at'], name='ops_opsaler_company_04ea1b_idx')],
            },
        ),
        migrations.CreateModel(
            name='OpsAlertSnooze',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_by_email', models.EmailField(blank=True, default='', max_length=254)),
                ('source', models.CharField(choices=[('stripe_webhook', 'Stripe webhook'), ('email', 'Email'), ('slow_request', 'Slow request'), ('auth', 'Auth'), ('throttle', 'Throttle'), ('launch_gate', 'Launch gate'), ('backup', 'Backup'), ('restore_test', 'Restore test'), ('ops_dashboard', 'Ops dashboard'), ('probe', 'Probe')], db_index=True, max_length=32)),
                ('snoozed_until', models.DateTimeField(db_index=True)),
                ('reason', models.CharField(blank=True, default='', max_length=200)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ops_alert_snoozes', to='companies.company')),
            ],
            options={
                'ordering': ['-snoozed_until'],
                'indexes': [models.Index(fields=['source', 'snoozed_until'], name='ops_snooze_source_until_idx'), models.Index(fields=['company', 'source', 'snoozed_until'], name='ops_snooze_co_source_until_idx')],
            },
        ),
        migrations.CreateModel(
            name='OpsCheckRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_by_email', models.EmailField(blank=True, default='', max_length=254)),
                ('kind', models.CharField(choices=[('smoke', 'Smoke Test'), ('invariants', 'Invariants'), ('idempotency', 'Idempotency Scan'), ('readiness', 'Readiness Check'), ('template_sanity', 'Template sanity'), ('url_sanity', 'URL sanity')], db_index=True, max_length=32)),
                ('args', models.JSONField(blank=True, default=dict)),
                ('is_ok', models.BooleanField(db_index=True, default=False)),
                ('duration_ms', models.IntegerField(default=0)),
                ('output_text', models.TextField(blank=True, default='')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ops_check_runs', to='companies.company')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['kind', 'created_at'], name='ops_opschec_kind_516b79_idx'), models.Index(fields=['company', 'created_at'], name='ops_opschec_company_cc4f77_idx'), models.Index(fields=['is_ok', 'created_at'], name='ops_opschec_is_ok_da90d1_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserPresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_seen', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presence_rows', to='companies.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presence_rows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['company', 'last_seen'], name='ops_userpre_company_f4154b_idx'), models.Index(fields=['last_seen'], name='ops_userpre_last_se_b58ff0_idx')],
                'unique_together': {('user', 'company')},
            },
        ),
    ]
