# Generated by ChatGPT for EZ360PM Pack 3
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0002_company_suspension_fields"),
        ("accounts", "0003_user_force_logout_at"),
        ("ops", "0005_siteconfig_billing_trial_and_notify"),
    ]

    operations = [
        migrations.CreateModel(
            name="OpsActionLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("actor_email", models.EmailField(blank=True, db_index=True, default="", max_length=254)),
                ("action", models.CharField(db_index=True, max_length=80)),
                ("summary", models.CharField(blank=True, default="", max_length=240)),
                ("meta", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.CharField(blank=True, default="", max_length=64)),
                ("user_agent", models.CharField(blank=True, default="", max_length=255)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ops_actions",
                        to="accounts.user",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ops_actions",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="opsactionlog",
            index=models.Index(fields=["company", "created_at"], name="ops_act_co_created_idx"),
        ),
        migrations.AddIndex(
            model_name="opsactionlog",
            index=models.Index(fields=["action", "created_at"], name="ops_act_action_created_idx"),
        ),
        migrations.AddIndex(
            model_name="opsactionlog",
            index=models.Index(fields=["actor_email", "created_at"], name="ops_act_actor_created_idx"),
        ),
    ]
