# Generated by Django 6.0.2 on 2026-02-21 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0007_ops_stripe_actions_and_presets'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='opsactionlog',
            new_name='ops_opsacti_company_c680be_idx',
            old_name='ops_act_co_created_idx',
        ),
        migrations.RenameIndex(
            model_name='opsactionlog',
            new_name='ops_opsacti_action_fbd694_idx',
            old_name='ops_act_action_created_idx',
        ),
        migrations.RenameIndex(
            model_name='opsactionlog',
            new_name='ops_opsacti_actor_e_47a5c4_idx',
            old_name='ops_act_actor_created_idx',
        ),
        migrations.RenameIndex(
            model_name='opsstripeaction',
            new_name='ops_opsstri_status_d1084f_idx',
            old_name='ops_stripe_status_created_idx',
        ),
        migrations.RenameIndex(
            model_name='opsstripeaction',
            new_name='ops_opsstri_company_d4ed6a_idx',
            old_name='ops_stripe_co_st_cr_idx',
        ),
        migrations.RenameIndex(
            model_name='opsstripeaction',
            new_name='ops_opsstri_action__c07603_idx',
            old_name='ops_stripe_type_created_idx',
        ),
    ]
