# Generated by Django 6.0.2 on 2026-02-22 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0008_rename_ops_act_co_created_idx_ops_opsacti_company_c680be_idx_and_more'),
        ('ops', '0011_siteconfig_risk_scoring'),
    ]

    operations = [
    ]
