# Generated by Django 6.0.2 on 2026-02-22 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0012_merge_20260221_2028'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='companylifecycleevent',
            new_name='ops_company_event_t_940cda_idx',
            old_name='ops_life_ev_type_oc_idx',
        ),
        migrations.RenameIndex(
            model_name='companylifecycleevent',
            new_name='ops_company_company_9fa83f_idx',
            old_name='ops_life_co_type_oc_idx',
        ),
        migrations.RenameIndex(
            model_name='opsroleassignment',
            new_name='ops_opsrole_role_b252eb_idx',
            old_name='ops_opsrole_role_created_idx',
        ),
        migrations.RenameIndex(
            model_name='opsroleassignment',
            new_name='ops_opsrole_user_id_abfa3c_idx',
            old_name='ops_opsrole_user_created_idx',
        ),
    ]
