# Generated by Django 6.0.2 on 2026-02-22 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0012_opscompanyviewpreset_owner'),
        ('ops', '0013_rename_ops_life_ev_type_oc_idx_ops_company_event_t_940cda_idx_and_more'),
    ]

    operations = [
    ]
