# Generated by Django 6.0.2 on 2026-02-22 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0013_company_risk_snapshots_and_two_person'),
        ('ops', '0014_merge_20260222_0913'),
    ]

    operations = [
    ]
