# Generated by Django 6.0.2 on 2026-02-22 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0014_outbound_email_log'),
        ('ops', '0015_merge_20260222_1103'),
    ]

    operations = [
    ]
