# Generated by Django 6.0.2 on 2026-02-22 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0016_merge_20260222_1641'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='outboundemaillog',
            new_name='ops_outboun_status_f3a76c_idx',
            old_name='ops_outbound_status_created_idx',
        ),
        migrations.RenameIndex(
            model_name='outboundemaillog',
            new_name='ops_outboun_templat_2a5b3f_idx',
            old_name='ops_outbound_template_created_idx',
        ),
        migrations.RenameIndex(
            model_name='outboundemaillog',
            new_name='ops_outboun_company_68fdcc_idx',
            old_name='ops_outbound_company_created_idx',
        ),
        migrations.AlterField(
            model_name='opscheckrun',
            name='kind',
            field=models.CharField(choices=[('smoke', 'Smoke Test'), ('invariants', 'Invariants'), ('idempotency', 'Idempotency Scan'), ('readiness', 'Readiness Check'), ('template_sanity', 'Template sanity'), ('url_sanity', 'URL sanity'), ('backup_verify', 'Backup verification')], db_index=True, max_length=32),
        ),
    ]
