# Generated by Django 6.0.2 on 2026-02-16 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0016_opscheckrun'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='opscheckrun',
            new_name='ops_opschec_kind_516b79_idx',
            old_name='ops_opscheck_kind_crea_idx',
        ),
        migrations.RenameIndex(
            model_name='opscheckrun',
            new_name='ops_opschec_company_cc4f77_idx',
            old_name='ops_opscheck_comp_crea_idx',
        ),
        migrations.RenameIndex(
            model_name='opscheckrun',
            new_name='ops_opschec_is_ok_da90d1_idx',
            old_name='ops_opscheck_ok_crea_idx',
        ),
    ]
