# Generated by Django 6.0.2 on 2026-02-16 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0017_rename_ops_opscheck_kind_crea_idx_ops_opschec_kind_516b79_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opscheckrun',
            name='kind',
            field=models.CharField(choices=[('smoke', 'Smoke Test'), ('invariants', 'Invariants'), ('idempotency', 'Idempotency Scan'), ('readiness', 'Readiness Check'), ('template_sanity', 'Template sanity')], db_index=True, max_length=32),
        ),
    ]
