# Generated by Django 6.0.2 on 2026-02-16 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0018_alter_opscheckrun_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opscheckrun',
            name='kind',
            field=models.CharField(choices=[('smoke', 'Smoke Test'), ('invariants', 'Invariants'), ('idempotency', 'Idempotency Scan'), ('readiness', 'Readiness Check'), ('template_sanity', 'Template sanity'), ('url_sanity', 'URL sanity')], db_index=True, max_length=32),
        ),
    ]
