# Generated by ChatGPT on 2026-02-13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="journalentry",
            name="posted_at",
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
