# Generated by Django 6.0.2 on 2026-02-14 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0004_alter_opsalertevent_source'),
        ('ops', '0004_backup_models'),
    ]

    operations = [
    ]
