# Generated by Django 6.0.2 on 2026-02-14 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0008_rename_ops_releas_environment_8d0b27_idx_ops_release_environ_2aebc9_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='storagesmoketest',
            name='ops_storage_kind_d3ea22_idx',
        ),
        migrations.RemoveIndex(
            model_name='storagesmoketest',
            name='ops_storage_ok_b08282_idx',
        ),
        migrations.DeleteModel(
            name='StorageSmokeTest',
        ),
    ]
