# Generated by Django 6.0.2 on 2026-02-13 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_rename_payments_ref_company_payment_created_idx_payments_pa_company_358cef_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='clientcreditapplication',
            name='payments_cl_company_4382e3_idx',
        ),
        migrations.RemoveIndex(
            model_name='clientcreditapplication',
            name='payments_cl_company_d51c22_idx',
        ),
    ]
