# Generated by Django 6.0.2 on 2026-02-17 02:57

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('revision', models.BigIntegerField(default=0)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_by_device', models.UUIDField(blank=True, null=True)),
                ('first_name', models.CharField(blank=True, default='', max_length=80)),
                ('last_name', models.CharField(blank=True, default='', max_length=80)),
                ('company_name', models.CharField(blank=True, default='', max_length=160)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('internal_note', models.TextField(blank=True, default='')),
                ('address1', models.CharField(blank=True, default='', max_length=200)),
                ('address2', models.CharField(blank=True, default='', max_length=200)),
                ('city', models.CharField(blank=True, default='', max_length=120)),
                ('state', models.CharField(blank=True, default='', max_length=2)),
                ('zip_code', models.CharField(blank=True, default='', max_length=12)),
                ('credit_cents', models.BigIntegerField(default=0)),
                ('outstanding_cents', models.BigIntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='companies.company')),
                ('updated_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClientImportBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('original_filename', models.CharField(blank=True, default='', max_length=260)),
                ('csv_content', models.TextField(blank=True, default='')),
                ('imported_at', models.DateTimeField(blank=True, null=True)),
                ('last_summary', models.JSONField(blank=True, default=dict)),
                ('last_report_csv', models.TextField(blank=True, default='')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_import_batches', to='companies.company')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_import_batches', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClientImportMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('mapping', models.JSONField(blank=True, default=dict)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_import_mappings', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_import_mappings_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_import_mappings_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClientPhone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('revision', models.BigIntegerField(default=0)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_by_device', models.UUIDField(blank=True, null=True)),
                ('phone_type', models.CharField(choices=[('mobile', 'Mobile'), ('work', 'Work'), ('home', 'Home'), ('other', 'Other')], default='mobile', max_length=20)),
                ('number', models.CharField(max_length=40)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='crm.client')),
                ('updated_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['company', 'company_name', 'last_name', 'first_name'], name='crm_client_company_b90cd3_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['company', 'updated_at'], name='crm_client_company_19dafc_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['company', 'email'], name='crm_client_company_9752a4_idx'),
        ),
        migrations.AddIndex(
            model_name='clientimportmapping',
            index=models.Index(fields=['company', 'name'], name='crm_clienti_company_7dd05c_idx'),
        ),
        migrations.AddIndex(
            model_name='clientimportmapping',
            index=models.Index(fields=['company', 'is_default'], name='crm_clienti_company_ba4bc8_idx'),
        ),
        migrations.AddConstraint(
            model_name='clientimportmapping',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='uniq_client_import_mapping_name_per_company'),
        ),
        migrations.AddIndex(
            model_name='clientphone',
            index=models.Index(fields=['client'], name='crm_clientp_client__7b16b2_idx'),
        ),
    ]
