# Generated by Django 6.0.2 on 2026-02-15 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_client_company_email_index'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='client',
            new_name='crm_client_company_9752a4_idx',
            old_name='crm_client_company_email_idx',
        ),
    ]
