# Generated by ChatGPT Phase 5B
from __future__ import annotations

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="default_invoice_due_days",
            field=models.PositiveIntegerField(
                default=30,
                help_text="Default number of days until invoice due date (used when creating new invoices).",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="default_estimate_valid_days",
            field=models.PositiveIntegerField(
                default=30,
                help_text="Default number of days an estimate/proposal remains valid (used when creating new documents).",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="default_sales_tax_percent",
            field=models.DecimalField(
                max_digits=6,
                decimal_places=3,
                default=Decimal("0.000"),
                help_text="Default sales tax percentage for guidance (does not automatically apply tax to line items).",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="default_line_items_taxable",
            field=models.BooleanField(
                default=False,
                help_text="Default 'Taxable' checkbox for new document line items.",
            ),
        ),
    ]
