# Generated by Django 6.0.2 on 2026-02-16 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_remove_vendor'),
        ('crm', '0003_rename_crm_client_company_email_idx_crm_client_company_9752a4_idx'),
    ]

    operations = [
    ]
