# Generated by Django 6.0.2 on 2026-02-17 02:57

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('revision', models.BigIntegerField(default=0)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_by_device', models.UUIDField(blank=True, null=True)),
                ('item_type', models.CharField(choices=[('service', 'Service'), ('product', 'Product')], default='service', max_length=20)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True, default='')),
                ('unit_price_cents', models.BigIntegerField(default=0)),
                ('tax_behavior', models.CharField(choices=[('non_taxable', 'Non-taxable'), ('taxable', 'Taxable')], default='non_taxable', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_items', to='companies.company')),
                ('updated_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['company', 'item_type', 'is_active'], name='catalog_cat_company_b97a82_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'name'), name='uniq_company_catalog_item_name')],
            },
        ),
    ]
