# Generated by Django 5.1 on 2025-09-06 00:57

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=160, null=True)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('admin_first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('admin_last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('admin_phone', models.CharField(blank=True, max_length=50)),
                ('address_1', models.CharField(blank=True, max_length=200, null=True, verbose_name='Address line 1')),
                ('address_2', models.CharField(blank=True, max_length=200, null=True, verbose_name='Address line 2')),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True, verbose_name='State / Province')),
                ('zip_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='ZIP / Postal code')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'company',
                'verbose_name_plural': 'companies',
                'ordering': ('-created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='CompanyInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member')], default='member', max_length=12)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('canceled', 'Canceled')], default='pending', max_length=12)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='company.company')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_company_invites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'company invite',
                'verbose_name_plural': 'company invites',
                'ordering': ('-sent_at',),
            },
        ),
        migrations.CreateModel(
            name='CompanyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member')], default='member', max_length=12)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('job_title', models.CharField(blank=True, max_length=120)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='company.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'company member',
                'verbose_name_plural': 'company members',
                'ordering': ('-joined_at',),
            },
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['owner', 'name'], name='company_com_owner_i_f112e3_idx'),
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='uniq_owner_company_name'),
        ),
        migrations.AddIndex(
            model_name='companyinvite',
            index=models.Index(fields=['company', 'email'], name='company_com_company_35b778_idx'),
        ),
        migrations.AddIndex(
            model_name='companyinvite',
            index=models.Index(fields=['token'], name='company_com_token_6d89c5_idx'),
        ),
        migrations.AddIndex(
            model_name='companyinvite',
            index=models.Index(fields=['status', 'sent_at'], name='company_com_status_d2f2e1_idx'),
        ),
        migrations.AddIndex(
            model_name='companymember',
            index=models.Index(fields=['company', 'role'], name='company_com_company_ca8bdc_idx'),
        ),
        migrations.AddIndex(
            model_name='companymember',
            index=models.Index(fields=['user'], name='company_com_user_id_1d1f0e_idx'),
        ),
        migrations.AddConstraint(
            model_name='companymember',
            constraint=models.UniqueConstraint(fields=('company', 'user'), name='uniq_company_member'),
        ),
    ]
