# Generated by Django 6.0.2 on 2026-02-21 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_stripe_connect_account'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='stripeconnectaccount',
            new_name='payments_st_company_3455fd_idx',
            old_name='payments_str_company_status_idx',
        ),
        migrations.RenameIndex(
            model_name='stripeconnectaccount',
            new_name='payments_st_stripe__aad06b_idx',
            old_name='payments_str_stripe_account_idx',
        ),
    ]
