# Generated by Django 6.0.2 on 2026-02-13 20:10
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0002_initial"),
        ("companies", "0001_initial"),
        ("crm", "0001_initial"),
        ("documents", "0001_initial"),
        ("payments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientCreditApplication",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("revision", models.BigIntegerField(default=0)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("cents", models.BigIntegerField()),
                ("memo", models.CharField(blank=True, default="", max_length=240)),
                ("applied_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("client", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="credit_applications", to="crm.client")),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="credit_applications", to="companies.company")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="companies.employeeprofile")),
                ("invoice", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="credit_applications", to="documents.document")),
                ("journal_entry", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="credit_applications", to="accounting.journalentry")),
                ("updated_by_user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="payments_clientcreditapplication_updates", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["company", "client", "applied_at"], name="payments_ccap_company__c3c842_idx"),
                    models.Index(fields=["company", "invoice"], name="payments_ccap_company__6bd8f3_idx"),
                ],
            },
        ),
    ]
