# Generated by ChatGPT on 2026-02-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ops", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfig",
            name="maintenance_mode_enabled",
            field=models.BooleanField(
                default=False,
                help_text="When enabled, the site shows a maintenance notice to non-staff users.",
            ),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="maintenance_message",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Optional message displayed on the maintenance page.",
            ),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="maintenance_allow_staff",
            field=models.BooleanField(
                default=True,
                help_text="If enabled, staff users may continue to use the app during maintenance.",
            ),
        ),
    ]
