# Generated by Django 6.0.2 on 2026-02-13 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_plan_tiers_interval_extra_seats'),
    ]

    operations = [
        # Render/production hardening:
        # Some environments may not have the old auto-generated index names (e.g.,
        # prior migrations created different names, or the index was dropped manually).
        # Django's RenameIndex calls schema_editor.rename_index(), which fails hard
        # if the old name doesn't exist. We make this migration idempotent:
        # - rename old->new only if the old exists and new doesn't
        # - create the expected index if neither exists
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
DO $$
BEGIN
    -- plan/billing_interval/status composite index
    IF to_regclass('public.billing_com_plan_int_status_idx') IS NOT NULL
       AND to_regclass('public.billing_com_plan_1b5666_idx') IS NULL THEN
        EXECUTE 'ALTER INDEX billing_com_plan_int_status_idx RENAME TO billing_com_plan_1b5666_idx';
    END IF;

    IF to_regclass('public.billing_com_plan_1b5666_idx') IS NULL THEN
        EXECUTE 'CREATE INDEX IF NOT EXISTS billing_com_plan_1b5666_idx '
                'ON billing_companysubscription (plan, billing_interval, status)';
    END IF;

    -- trial_ends_at index
    IF to_regclass('public.billing_com_trial_ends_idx') IS NOT NULL
       AND to_regclass('public.billing_com_trial_e_a6b689_idx') IS NULL THEN
        EXECUTE 'ALTER INDEX billing_com_trial_ends_idx RENAME TO billing_com_trial_e_a6b689_idx';
    END IF;

    IF to_regclass('public.billing_com_trial_e_a6b689_idx') IS NULL THEN
        EXECUTE 'CREATE INDEX IF NOT EXISTS billing_com_trial_e_a6b689_idx '
                'ON billing_companysubscription (trial_ends_at)';
    END IF;
END $$;
""",
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.RenameIndex(
                    model_name='companysubscription',
                    new_name='billing_com_plan_1b5666_idx',
                    old_name='billing_com_plan_int_status_idx',
                ),
                migrations.RenameIndex(
                    model_name='companysubscription',
                    new_name='billing_com_trial_e_a6b689_idx',
                    old_name='billing_com_trial_ends_idx',
                ),
            ],
        ),
    ]
