# Generated by Django 6.0.2 on 2026-02-13 13:48

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_event_id', models.CharField(max_length=100, unique=True)),
                ('event_type', models.CharField(blank=True, default='', max_length=200)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('ok', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True, default='')),
                ('payload_json', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['event_type'], name='billing_bil_event_t_a4664b_idx'), models.Index(fields=['received_at'], name='billing_bil_receive_d23cdc_idx')],
            },
        ),
        migrations.CreateModel(
            name='CompanySubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('revision', models.BigIntegerField(default=0)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_by_device', models.UUIDField(blank=True, null=True)),
                ('plan', models.CharField(choices=[('standard', 'Standard'), ('premium', 'Premium')], default='standard', max_length=20)),
                ('seat_tier', models.CharField(choices=[('solo', 'Solo'), ('up_to_5', 'Up to 5'), ('up_to_10', 'Up to 10'), ('up_to_100', 'Up to 100')], default='solo', max_length=20)),
                ('status', models.CharField(choices=[('trialing', 'Trialing'), ('active', 'Active'), ('past_due', 'Past Due'), ('canceled', 'Canceled'), ('ended', 'Ended')], default='trialing', max_length=20)),
                ('trial_started_at', models.DateTimeField(blank=True, null=True)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('stripe_customer_id', models.CharField(blank=True, default='', max_length=80)),
                ('stripe_subscription_id', models.CharField(blank=True, default='', max_length=80)),
                ('stripe_cancel_at_period_end', models.BooleanField(default=False)),
                ('stripe_cancel_at', models.DateTimeField(blank=True, null=True)),
                ('stripe_canceled_at', models.DateTimeField(blank=True, null=True)),
                ('last_license_check_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='companies.company')),
                ('updated_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['plan', 'status'], name='billing_com_plan_dfe1e0_idx'), models.Index(fields=['trial_ends_at'], name='billing_com_trial_e_a6b689_idx')],
            },
        ),
    ]
