# Generated by Django 6.0.2 on 2026-02-17 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_dashboard_layout'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='dashboardlayout',
            new_name='core_dashbo_company_5eb80a_idx',
            old_name='core_dashbo_company_2d7a7a_idx',
        ),
    ]
