# Generated by ChatGPT on 2026-02-19
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0003_subscription_ops_notified_active_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanCatalog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(choices=[("starter", "Starter"), ("professional", "Professional"), ("premium", "Premium")], max_length=20, unique=True)),
                ("name", models.CharField(max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=10)),
                ("monthly_price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("annual_price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("stripe_monthly_price_id", models.CharField(blank=True, default="", max_length=120)),
                ("stripe_annual_price_id", models.CharField(blank=True, default="", max_length=120)),
                ("included_seats", models.PositiveSmallIntegerField(default=1)),
                ("trial_days", models.PositiveSmallIntegerField(default=14)),
            ],
            options={
                "verbose_name": "Plan (catalog)",
                "verbose_name_plural": "Plans (catalog)",
                "ordering": ["sort_order", "monthly_price"],
            },
        ),
        migrations.CreateModel(
            name="SeatAddonConfig",
            fields=[
                ("id", models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ("monthly_price", models.DecimalField(decimal_places=2, default=9.99, max_digits=8)),
                ("annual_price", models.DecimalField(decimal_places=2, default=99.99, max_digits=8)),
                ("stripe_monthly_price_id", models.CharField(blank=True, default="", max_length=120)),
                ("stripe_annual_price_id", models.CharField(blank=True, default="", max_length=120)),
            ],
            options={
                "verbose_name": "Seat add-on config",
                "verbose_name_plural": "Seat add-on config",
            },
        ),
    ]
