# Generated by Django 5.1 on 2025-09-06 00:57

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('invoices', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7)),
                ('is_billable', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('reject_reason', models.CharField(blank=True, default='', max_length=200)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_timeentries', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='company.company')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_entries', to='invoices.invoice')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_timeentry',
                'ordering': ('-start_time', '-id'),
                'indexes': [models.Index(fields=['project', 'user', 'start_time'], name='core_timeen_project_55ff4e_idx'), models.Index(fields=['project', 'status', 'start_time'], name='core_timeen_project_550d36_idx'), models.Index(fields=['user', 'status', 'start_time'], name='core_timeen_user_id_c1e5e8_idx'), models.Index(fields=['company', 'start_time'], name='core_timeen_company_b3dcfe_idx'), models.Index(fields=['invoice'], name='core_timeen_invoice_3a49b4_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('end_time__isnull', True)), fields=('user', 'company'), name='uniq_running_timeentry_per_user_company')],
            },
        ),
    ]
