# Generated by Django 6.0.2 on 2026-02-17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
        ("projects", "0001_initial"),
        ("timetracking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="timetrackingsettings",
            name="last_project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="time_settings_last_project",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="timetrackingsettings",
            name="last_service_catalog_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="time_settings_last_service",
                to="catalog.catalogitem",
            ),
        ),
    ]
