# Generated by Django 6.0.2 on 2026-02-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timetracking", "0002_timetrackingsettings_timer_defaults"),
    ]

    operations = [
        migrations.AddField(
            model_name="timetrackingsettings",
            name="last_service_name",
            field=models.CharField(max_length=200, blank=True, default=""),
        ),
        migrations.AddField(
            model_name="timetrackingsettings",
            name="last_note",
            field=models.TextField(blank=True, default=""),
        ),
    ]
