# Generated by Django 6.0.2 on 2026-02-13 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_merge_20260213_1812'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='clientcreditapplication',
            new_name='payments_cl_company_4382e3_idx',
            old_name='payments_cca_company_client_applied_idx',
        ),
        migrations.RenameIndex(
            model_name='clientcreditapplication',
            new_name='payments_cl_company_d51c22_idx',
            old_name='payments_cca_company_invoice_idx',
        ),
        migrations.RenameIndex(
            model_name='clientcreditledgerentry',
            new_name='payments_cl_company_4632e3_idx',
            old_name='payments_ccle_company_client_created_idx',
        ),
        migrations.RenameIndex(
            model_name='clientcreditledgerentry',
            new_name='payments_cl_company_69a678_idx',
            old_name='payments_ccle_company_invoice_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='payments_pa_company_ab6995_idx',
            old_name='payments_pa_company_status_date_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='payments_pa_company_e146bf_idx',
            old_name='payments_pa_company_invoice_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='payments_pa_company_1febf5_idx',
            old_name='payments_pa_company_client_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='payments_pa_company_ae29b6_idx',
            old_name='payments_pa_company_pi_idx',
        ),
    ]
